/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.82
 * Generated at: 2018-05-01 07:33:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class EmployeeSet_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("    <title>员工账号设置</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\"/>\r\n");
      out.write("    <script src=\"js/jquery-1.7.2.min.js\"></script>\r\n");
      out.write("    <script src=\"js/bootstrap.js\"></script>\r\n");
      out.write("    <script src=\"js/vue.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\twindow.onload = function(){\r\n");
      out.write("\t\t\tnew Vue({\r\n");
      out.write("\t\t\t\tel:'#box',\r\n");
      out.write("\t\t\t\tdata:{\r\n");
      out.write("\t\t\t\t\tmyData:[],\r\n");
      out.write("\t\t\t\t\tposition:\"\",\r\n");
      out.write("\t\t\t\t\tempID:\"\",\r\n");
      out.write("\t\t\t\t\tempname:\"\",\r\n");
      out.write("\t\t\t\t\temppw:\"\",\r\n");
      out.write("\t\t\t\t\temppwcheck:\"\",\r\n");
      out.write("\t\t\t\t\tnowIndex:-100\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tmethods:{\r\n");
      out.write("\t\t\t\t\tadd:function(){\r\n");
      out.write("\t\t\t\t\t\tvar judge;\r\n");
      out.write("\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\turl:\"EmployeeAdd\",\r\n");
      out.write("\t\t\t\t\t\t\tasync:false,\r\n");
      out.write("\t\t\t\t\t\t\ttype:\"post\",      \r\n");
      out.write("\t\t\t\t\t\t\tdataType:\"text\",\r\n");
      out.write("\t\t\t\t\t\t\tdata:{\r\n");
      out.write("\t\t\t\t\t\t\t\t\"position\":document.getElementById('position').options[document.getElementById('position').selectedIndex].value,\r\n");
      out.write("\t\t\t\t\t\t\t\t\"empID\":this.empID,\r\n");
      out.write("\t\t\t\t\t\t\t\t\"empname\":this.empname,\r\n");
      out.write("\t\t\t\t\t\t\t\t\"emppw\":this.emppw,\r\n");
      out.write("\t\t\t\t\t\t\t\t\"emppwcheck\":this.emppwcheck\r\n");
      out.write("                            },\r\n");
      out.write("\t\t\t\t\t\t\tsuccess:function(Result)\r\n");
      out.write("\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\tjudge=Result;\r\n");
      out.write("\t\t\t\t\t\t\t\talert(judge);\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\terror:function(){alert(\"数据传输失败!\");},\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\tif(judge==\"员工账号添加成功\")\r\n");
      out.write("\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\tthis.myData.push({\r\n");
      out.write("\t\t\t\t\t\t\t\tposition:document.getElementById('position').options[document.getElementById('position').selectedIndex].value,\r\n");
      out.write("  \t\t\t\t\t\t\t\tempID:this.empID,\r\n");
      out.write("  \t\t\t\t\t\t\t\tempname:this.empname,\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tthis.position=\"\";\r\n");
      out.write("\t\t\t\t\t\tthis.empID=\"\";\r\n");
      out.write("\t\t\t\t\t\tthis.empname=\"\";\r\n");
      out.write("\t\t\t\t\t\tthis.emppw=\"\";\r\n");
      out.write("\t\t\t\t\t\tthis.emppwcheck=\"\";\r\n");
      out.write("                     },\r\n");
      out.write("                     ini:function(){\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                    \tdocument.getElementById(\"load\").style.display=\"none\";\r\n");
      out.write("                    },\r\n");
      out.write("\t\t\t\t\tdel:function(n){\r\n");
      out.write("\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\turl:\"EmployeeDel\",\r\n");
      out.write("\t\t\t\t\t\t\ttype:\"post\",      \r\n");
      out.write("\t\t\t\t\t\t\tdataType:\"text\",\r\n");
      out.write("\t\t\t\t\t\t\tdata:{\"empID\":this.myData[n].empID},\r\n");
      out.write("\t\t\t\t\t\t\tsuccess:function(Result){alert(Result);},\r\n");
      out.write("\t\t\t\t\t\t\terror:function(){alert(\"数据传输失败!\");}\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\tthis.myData.splice(n,1);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container\" id=\"box\">\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label for=\"position\">职务：</label></br>\r\n");
      out.write("\t\t\t<select id=\"position\">\r\n");
      out.write("\t\t\t\t<option value=\"前台接待员\">&nbsp;&nbsp;前台接待员</option>\r\n");
      out.write("\t\t\t\t<option value=\"经理\">&nbsp;&nbsp;经理</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label for=\"empID\">员工号：</label>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"empID\" class=\"form-control\" style=\"height:25px;\" v-model=\"empID\" placeholder=\"输入员工号\"/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label for=\"empname\">姓名：</label>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"empname\" class=\"form-control\" style=\"height:25px;\" v-model=\"empname\" placeholder=\"输入姓名\"/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label for=\"emppw\">密码：</label>\r\n");
      out.write("\t\t\t<input type=\"password\" id=\"emppw\" class=\"form-control\" style=\"height:25px;\" v-model=\"emppw\" placeholder=\"输入密码\"/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label for=\"emppwcheck\">密码验证：</label>\r\n");
      out.write("\t\t\t<input type=\"password\" id=\"emppwcheck\" class=\"form-control\" style=\"height:25px;\" v-model=\"emppwcheck\" placeholder=\"再次输入密码\"/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<input type=\"button\"  value=\"添加\" class=\"btn btn-primary\" v-on:click=\"add()\"/>\r\n");
      out.write("\t\t\t<input type=\"reset\"  value=\"重置\" class=\"btn btn-danger\"/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</hr>\r\n");
      out.write("\t\t<table class=\"table table-bordered table-hover\">\r\n");
      out.write("\t\t\t<caption class=\"h3 text-info\">员工信息表</caption>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th class=\"text-center\">职务</th>\r\n");
      out.write("\t\t\t\t<th class=\"text-center\">员工号</th>\r\n");
      out.write("\t\t\t\t<th class=\"text-center\">姓名</th>\r\n");
      out.write("\t\t\t\t<th class=\"text-center\">操作</th>\r\n");
      out.write("\t\t\t</tr> \r\n");
      out.write("\t\t\t<tr class=\"text-center\" v-for=\"item in myData\">\r\n");
      out.write("\t\t\t\t<td>{{item.position}}</td>\r\n");
      out.write("\t\t\t\t<td>{{item.empID}}</td>\r\n");
      out.write("\t\t\t\t<td>{{item.empname}}</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-primary btn-sm\" data-toggle=\"modal\" data-target=\"#layer\" v-on:click=\"nowIndex=$index\">删除</button>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("             </tr>\r\n");
      out.write("             <tr id=\"load\" class=\"text-center\">\r\n");
      out.write("             \t <td colspan=\"4\" class=\"text-center\">\r\n");
      out.write("                     <button class=\"btn btn-primary\" v-on:click=\"ini()\">加载已有数据</button>\r\n");
      out.write("                 </td>\r\n");
      out.write("             </tr>\r\n");
      out.write("             <tr class=\"text-center\" v-show=\"myData.length!=0\">\r\n");
      out.write("             \t <td colspan=\"4\" class=\"text-center\">\r\n");
      out.write("                     <button class=\"btn btn-primary\" onclick=\"location.reload()\">刷新</button>\r\n");
      out.write("                 </td>\r\n");
      out.write("             </tr>\r\n");
      out.write("         </table>\r\n");
      out.write("         <div role=\"dialog\" class=\"modal fade\" id=\"layer\" data-index=\"{{nowIndex}}\">\r\n");
      out.write("              <div class=\"modal-dialog\">\r\n");
      out.write("                  <div class=\"modal-content\">\r\n");
      out.write("                      <div class=\"modal-header\">\r\n");
      out.write("                          <button class=\"close\" data-dismiss=\"modal\">\r\n");
      out.write("                              <span>&times;</span>\r\n");
      out.write("                          </button>\r\n");
      out.write("                          <h4 class=\"modal-title\">确认删除吗？</h4>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"modal-body text-right\">\r\n");
      out.write("                          <button class=\"btn btn-primary btn-sm\" data-dismiss=\"modal\">取消</button>\r\n");
      out.write("                          <button class=\"btn btn-danger btn-sm\" data-dismiss=\"modal\" v-on:click=\"del(nowIndex)\">确认</button>\r\n");
      out.write("                      </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </div>\r\n");
      out.write("         </div>\r\n");
      out.write("     </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /EmployeeSet.jsp(63,6) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${data}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      // /EmployeeSet.jsp(63,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("emp");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\tthis.myData.push({\r\n");
            out.write(" \t\t\t\t\t\t\t\tposition:\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${emp.getPosition()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\",\r\n");
            out.write(" \t\t\t\t\t\t\t\tempID:\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${emp.getStaffid()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\",\r\n");
            out.write(" \t\t\t\t\t\t\t\tempname:\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${emp.getName()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\"\r\n");
            out.write(" \t\t\t\t\t\t\t})\r\n");
            out.write(" \t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
