/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.82
 * Generated at: 2018-05-01 07:33:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class managermenu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("\t<title>【515】酒店管理系统</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"plugins/layui/css/layui.css\" media=\"all\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"http://cdn.bootcss.com/font-awesome/4.6.0/css/font-awesome.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"build/css/app.css\" media=\"all\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"layui-layout layui-layout-admin kit-layout-admin\">\r\n");
      out.write("\t\t<div class=\"layui-header\">\r\n");
      out.write("\t\t\t<div class=\"layui-logo\">【515】酒店管理系统</div>\r\n");
      out.write("\t\t\t<ul class=\"layui-nav layui-layout-right kit-nav\" lay-filter=\"kitNavbar\" kit-navbar>\r\n");
      out.write("\t\t\t\t<li class=\"layui-nav-item\">\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:;\"><img src=\"http://m.zhengjinfan.cn/images/0.jpg\" class=\"layui-nav-img\">经理</a>\r\n");
      out.write("\t\t\t\t\t<dl class=\"layui-nav-child\">\r\n");
      out.write("\t\t\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" data-url=\"personalinfo.html\" data-icon=\"\" data-title=\"个人资料\" kit-target data-id=\"个人资料\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>个人资料</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</dd>\r\n");
      out.write("  \t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"layui-nav-item\">\r\n");
      out.write("\t\t\t\t\t<a href=\"SafeExit\"><i class=\"fa fa-sign-out\" aria-hidden=\"true\"></i>&nbsp&nbsp注销</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"layui-side layui-bg-black kit-side\">\r\n");
      out.write("\t\t\t<div class=\"layui-side-scroll\">\r\n");
      out.write("\t\t\t\t<div class=\"kit-side-fold\" style=\"height:42px;\"><i class=\"fa fa-navicon\"></i></div>\r\n");
      out.write("\t\t\t\t<ul class=\"layui-nav layui-nav-tree\" lay-filter=\"kitNavbar\" kit-navbar>\r\n");
      out.write("\t\t\t\t\t<li class=\"layui-nav-item\">\r\n");
      out.write(" \t\t\t\t\t\t<a href=\"javascript:;\"><i class=\"fa fa-gear fa-fw\"></i><span>&nbsp&nbsp基础设置</span></a>\r\n");
      out.write("\t\t\t\t\t\t<dl class=\"layui-nav-child\">\r\n");
      out.write(" \t\t\t\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"javascript:;\" data-url=\"RoomTypeSetServlet\" data-icon=\"\" data-title=\"客房类型设置\" kit-target data-id=\"客房类型设置\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-home fa-fw\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>&nbsp&nbsp客房类型设置&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"javascript:;\" data-url=\"RoomSetServlet\" data-icon=\"\" data-title=\"客房信息设置\" kit-target data-id=\"客房信息设置\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-hotel fa-fw\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>&nbsp&nbsp客房信息设置&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"javascript:;\" data-url=\"EmployeeServlet\" data-icon=\"\" data-title=\"账号设置\" kit-target data-id=\"账号设置\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-group fa-fw\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>&nbsp&nbsp账号设置&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"layui-nav-item\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"javascript:;\"><span></span><i class=\"fa fa-sitemap fa-fw\"></i><span>&nbsp&nbsp客房管理</span></a>\r\n");
      out.write("\t\t\t\t\t\t<dl class=\"layui-nav-child\">\r\n");
      out.write("\t\t\t\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"javascript:;\" data-url=\"RoomStatusStatistics.jsp\" data-icon=\"\" data-title=\"房态统计\" kit-target data-id=\"房态统计\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-bar-chart fa-fw\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>&nbsp&nbsp房态统计&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"layui-body\" id=\"container\">\r\n");
      out.write("\t\t\t<div class=\"layui-tab layui-tab-card kit-tab\" lay-filter=\"kitTab\">\r\n");
      out.write("\t\t\t\t<ul class=\"layui-tab-title\" style=\"width:100%\"></ul>\r\n");
      out.write("\t\t\t\t<div class=\"layui-tab-content\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("   \r\n");
      out.write("\t<script src=\"plugins/layui/layui.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tvar message;\r\n");
      out.write("\t\tlayui.config({base:'build/js/'}).use(['app','message'],\r\n");
      out.write("\t\tfunction(){\r\n");
      out.write("\t\t\tvar app=layui.app;\r\n");
      out.write("                \t$=layui.jquery;\r\n");
      out.write("                \tlayer=layui.layer;\r\n");
      out.write("            \t\tmessage=layui.message;      \r\n");
      out.write("\t\t\tapp.set({type:'iframe'}).init(); \r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
